Document: isisbrowser
Title: Debian isisbrowser Manual
Author: <insert document author here>
Abstract: This manual describes what isisbrowser is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/isisbrowser/isisbrowser.sgml.gz

Format: postscript
Files: /usr/share/doc/isisbrowser/isisbrowser.ps.gz

Format: text
Files: /usr/share/doc/isisbrowser/isisbrowser.text.gz

Format: HTML
Index: /usr/share/doc/isisbrowser/html/index.html
Files: /usr/share/doc/isisbrowser/html/*.html
